camel:
  springboot:
    # The Camel context name
    name: CamelRestRnec
  component:
    servlet:
      mapping:
        enabled: true
        context-path: /api/*

spring:
  servlet:
    multipart:
      enabled: true                  # Enable multipart support
      max-file-size: 10MB           # Maximum file size
      max-request-size: 10MB        # Maximum request size
      file-size-threshold: 10MB

# Binding health checks to a different port
# change actuator endpoints path
management:
  server:
    port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true